// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CheckRemoteGitRepo(arg1:string,arg2:string):Promise<boolean>;

export function Close():Promise<void>;

export function CreateHost(arg1:app.CreateHostOptions):Promise<app.HostInfo>;

export function CreateSession(arg1:app.CreateOptions):Promise<app.SessionInfo>;

export function DeleteHost(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetConfig():Promise<app.AppConfig>;

export function GetDirInfo(arg1:string):Promise<app.DirInfo>;

export function GetHosts():Promise<Array<app.HostInfo>>;

export function GetRemoteDirInfo(arg1:string,arg2:string):Promise<app.DirInfo>;

export function GetSessionStatus(arg1:string):Promise<app.SessionStatus>;

export function GetWebSocketPort():Promise<number>;

export function KillSession(arg1:string):Promise<void>;

export function ListRemoteDir(arg1:string,arg2:string):Promise<Array<app.RemoteDirEntry>>;

export function LoadSessions():Promise<Array<app.SessionInfo>>;

export function OpenSession(arg1:string):Promise<string>;

export function PauseSession(arg1:string):Promise<void>;

export function PollAllStatuses():Promise<Array<app.SessionStatus>>;

export function ResumeSession(arg1:string):Promise<void>;

export function SearchBranches(arg1:string,arg2:string):Promise<Array<string>>;

export function SearchRemoteBranches(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function SendPrompt(arg1:string,arg2:string):Promise<void>;

export function SetHostLastPath(arg1:string,arg2:string):Promise<void>;

export function StartSession(arg1:string):Promise<void>;

export function TestHost(arg1:app.CreateHostOptions,arg2:string):Promise<app.TestHostResult>;

export function UpdateHost(arg1:app.CreateHostOptions,arg2:string):Promise<void>;
