// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRemoteGitRepo(arg1, arg2) {
  return window['go']['app']['SessionAPI']['CheckRemoteGitRepo'](arg1, arg2);
}

export function Close() {
  return window['go']['app']['SessionAPI']['Close']();
}

export function CopyPath(arg1, arg2, arg3) {
  return window['go']['app']['SessionAPI']['CopyPath'](arg1, arg2, arg3);
}

export function CreateDirectory(arg1, arg2) {
  return window['go']['app']['SessionAPI']['CreateDirectory'](arg1, arg2);
}

export function CreateFile(arg1, arg2) {
  return window['go']['app']['SessionAPI']['CreateFile'](arg1, arg2);
}

export function CreateHost(arg1) {
  return window['go']['app']['SessionAPI']['CreateHost'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['app']['SessionAPI']['CreateSession'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['app']['SessionAPI']['DeleteHost'](arg1);
}

export function DeletePath(arg1, arg2) {
  return window['go']['app']['SessionAPI']['DeletePath'](arg1, arg2);
}

export function DeleteSession(arg1) {
  return window['go']['app']['SessionAPI']['DeleteSession'](arg1);
}

export function GetAllSymbols(arg1) {
  return window['go']['app']['SessionAPI']['GetAllSymbols'](arg1);
}

export function GetConfig() {
  return window['go']['app']['SessionAPI']['GetConfig']();
}

export function GetDiffFiles(arg1) {
  return window['go']['app']['SessionAPI']['GetDiffFiles'](arg1);
}

export function GetDirInfo(arg1) {
  return window['go']['app']['SessionAPI']['GetDirInfo'](arg1);
}

export function GetHosts() {
  return window['go']['app']['SessionAPI']['GetHosts']();
}

export function GetRemoteDirInfo(arg1, arg2) {
  return window['go']['app']['SessionAPI']['GetRemoteDirInfo'](arg1, arg2);
}

export function GetSessionStatus(arg1) {
  return window['go']['app']['SessionAPI']['GetSessionStatus'](arg1);
}

export function GetWebSocketPort() {
  return window['go']['app']['SessionAPI']['GetWebSocketPort']();
}

export function IndexSession(arg1) {
  return window['go']['app']['SessionAPI']['IndexSession'](arg1);
}

export function KillSession(arg1) {
  return window['go']['app']['SessionAPI']['KillSession'](arg1);
}

export function ListDirectory(arg1, arg2) {
  return window['go']['app']['SessionAPI']['ListDirectory'](arg1, arg2);
}

export function ListFiles(arg1) {
  return window['go']['app']['SessionAPI']['ListFiles'](arg1);
}

export function ListRemoteDir(arg1, arg2) {
  return window['go']['app']['SessionAPI']['ListRemoteDir'](arg1, arg2);
}

export function LoadSessions() {
  return window['go']['app']['SessionAPI']['LoadSessions']();
}

export function LookupSymbol(arg1, arg2) {
  return window['go']['app']['SessionAPI']['LookupSymbol'](arg1, arg2);
}

export function OpenSession(arg1) {
  return window['go']['app']['SessionAPI']['OpenSession'](arg1);
}

export function PauseSession(arg1) {
  return window['go']['app']['SessionAPI']['PauseSession'](arg1);
}

export function PollAllStatuses() {
  return window['go']['app']['SessionAPI']['PollAllStatuses']();
}

export function ReadFile(arg1, arg2) {
  return window['go']['app']['SessionAPI']['ReadFile'](arg1, arg2);
}

export function RenamePath(arg1, arg2, arg3) {
  return window['go']['app']['SessionAPI']['RenamePath'](arg1, arg2, arg3);
}

export function ResumeSession(arg1) {
  return window['go']['app']['SessionAPI']['ResumeSession'](arg1);
}

export function SearchBranches(arg1, arg2) {
  return window['go']['app']['SessionAPI']['SearchBranches'](arg1, arg2);
}

export function SearchRemoteBranches(arg1, arg2, arg3) {
  return window['go']['app']['SessionAPI']['SearchRemoteBranches'](arg1, arg2, arg3);
}

export function SelectFile(arg1) {
  return window['go']['app']['SessionAPI']['SelectFile'](arg1);
}

export function SendPrompt(arg1, arg2) {
  return window['go']['app']['SessionAPI']['SendPrompt'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['app']['SessionAPI']['SetContext'](arg1);
}

export function SetHostLastPath(arg1, arg2) {
  return window['go']['app']['SessionAPI']['SetHostLastPath'](arg1, arg2);
}

export function StartSession(arg1) {
  return window['go']['app']['SessionAPI']['StartSession'](arg1);
}

export function StopIndexer(arg1) {
  return window['go']['app']['SessionAPI']['StopIndexer'](arg1);
}

export function TestHost(arg1, arg2) {
  return window['go']['app']['SessionAPI']['TestHost'](arg1, arg2);
}

export function UpdateHost(arg1, arg2) {
  return window['go']['app']['SessionAPI']['UpdateHost'](arg1, arg2);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['app']['SessionAPI']['WriteFile'](arg1, arg2, arg3);
}
