// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function CheckRemoteGitRepo(arg1:string,arg2:string):Promise<boolean>;

export function Close():Promise<void>;

export function CopyPath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateDirectory(arg1:string,arg2:string):Promise<void>;

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function CreateHost(arg1:app.CreateHostOptions):Promise<app.HostInfo>;

export function CreateSession(arg1:app.CreateOptions):Promise<app.SessionInfo>;

export function DeleteHost(arg1:string):Promise<void>;

export function DeletePath(arg1:string,arg2:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetAllSymbols(arg1:string):Promise<Record<string, Array<app.Definition>>>;

export function GetConfig():Promise<app.AppConfig>;

export function GetDiffFiles(arg1:string):Promise<Array<app.DiffFileResult>>;

export function GetDirInfo(arg1:string):Promise<app.DirInfo>;

export function GetHosts():Promise<Array<app.HostInfo>>;

export function GetRemoteDirInfo(arg1:string,arg2:string):Promise<app.DirInfo>;

export function GetSessionStatus(arg1:string):Promise<app.SessionStatus>;

export function GetWebSocketPort():Promise<number>;

export function IndexSession(arg1:string):Promise<void>;

export function KillSession(arg1:string):Promise<void>;

export function KillShell(arg1:string):Promise<void>;

export function ListDirectory(arg1:string,arg2:string):Promise<Array<app.DirectoryEntry>>;

export function ListFiles(arg1:string):Promise<Array<string>>;

export function ListRemoteDir(arg1:string,arg2:string):Promise<Array<app.RemoteDirEntry>>;

export function LoadSessions():Promise<Array<app.SessionInfo>>;

export function LookupSymbol(arg1:string,arg2:string):Promise<Array<app.Definition>>;

export function OpenSession(arg1:string):Promise<string>;

export function PauseSession(arg1:string):Promise<void>;

export function PollAllStatuses():Promise<Array<app.SessionStatus>>;

export function ReadFile(arg1:string,arg2:string):Promise<string>;

export function RenamePath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResumeSession(arg1:string):Promise<void>;

export function SearchBranches(arg1:string,arg2:string):Promise<Array<string>>;

export function SearchRemoteBranches(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function SelectFile(arg1:string):Promise<string>;

export function SendPrompt(arg1:string,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetHostLastPath(arg1:string,arg2:string):Promise<void>;

export function SpawnShell(arg1:string):Promise<string>;

export function StartSession(arg1:string):Promise<void>;

export function StopIndexer(arg1:string):Promise<void>;

export function TouchSession(arg1:string):Promise<void>;

export function TestHost(arg1:app.CreateHostOptions,arg2:string):Promise<app.TestHostResult>;

export function UpdateHost(arg1:app.CreateHostOptions,arg2:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;
