import type { editor } from "monaco-editor";

export const catppuccinMocha: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6c7086", fontStyle: "italic" },
    { token: "keyword", foreground: "cba6f7" },
    { token: "string", foreground: "a6e3a1" },
    { token: "number", foreground: "fab387" },
    { token: "type", foreground: "f9e2af" },
    { token: "function", foreground: "89b4fa" },
    { token: "variable", foreground: "cdd6f4" },
    { token: "operator", foreground: "89dceb" },
    { token: "delimiter", foreground: "9399b2" },
    { token: "tag", foreground: "cba6f7" },
    { token: "attribute.name", foreground: "f9e2af" },
    { token: "attribute.value", foreground: "a6e3a1" },
  ],
  colors: {
    "editor.background": "#1e1e2e",
    "editor.foreground": "#cdd6f4",
    "editor.lineHighlightBackground": "#313244",
    "editor.selectionBackground": "#45475a",
    "editorCursor.foreground": "#f5e0dc",
    "editorLineNumber.foreground": "#6c7086",
    "editorLineNumber.activeForeground": "#cdd6f4",
    "editor.selectionHighlightBackground": "#45475a80",
    "editorBracketMatch.background": "#45475a",
    "editorBracketMatch.border": "#89b4fa",
    "editorIndentGuide.background": "#313244",
    "editorIndentGuide.activeBackground": "#45475a",
    "editorWidget.background": "#181825",
    "editorWidget.border": "#313244",
    "editorSuggestWidget.background": "#181825",
    "editorSuggestWidget.border": "#313244",
    "editorSuggestWidget.selectedBackground": "#313244",
    "input.background": "#313244",
    "input.border": "#45475a",
    "input.foreground": "#cdd6f4",
    "scrollbarSlider.background": "#45475a80",
    "scrollbarSlider.hoverBackground": "#585b7080",
  },
};
